### ISSUE TITLE
(URGENT) Failure in metanorma-cli

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#173]
From @petithug

Also reported by https://github.com/usnistgov/ACVP at https://github.com/metanorma/metanorma-cli/issues/172

```
$ metanorma version
[metanorma] Error: flavor gem metanorma-iso not present
[metanorma] Error: flavor gem metanorma-iec not present
[metanorma] Error: flavor gem metanorma-ietf not present
[metanorma] Error: flavor gem metanorma-gb not present
[metanorma] Error: flavor gem metanorma-cc not present
[metanorma] Error: flavor gem metanorma-csa not present
[metanorma] Error: flavor gem metanorma-iho not present
[metanorma] Error: flavor gem metanorma-m3aawg not present
[metanorma] Error: flavor gem metanorma-generic not present
[metanorma] Error: flavor gem metanorma-standoc not present
[metanorma] Error: flavor gem metanorma-un not present
[metanorma] Error: flavor gem metanorma-nist not present
[metanorma] Error: flavor gem metanorma-ogc not present
[metanorma] Error: flavor gem metanorma-itu not present
Metanorma 1.1.5
Metanorma::Cli 1.3.7.2
[metanorma] Error: flavor gem metanorma-iso not present
[metanorma] Error: flavor gem metanorma-iec not present
[metanorma] Error: flavor gem metanorma-ietf not present
[metanorma] Error: flavor gem metanorma-gb not present
[metanorma] Error: flavor gem metanorma-cc not present
[metanorma] Error: flavor gem metanorma-csa not present
[metanorma] Error: flavor gem metanorma-iho not present
[metanorma] Error: flavor gem metanorma-m3aawg not present
[metanorma] Error: flavor gem metanorma-generic not present
[metanorma] Error: flavor gem metanorma-standoc not present
[metanorma] Error: flavor gem metanorma-un not present
[metanorma] Error: flavor gem metanorma-nist not present
[metanorma] Error: flavor gem metanorma-ogc not present
[metanorma] Error: flavor gem metanorma-itu not present
```

**Comment by ronaldtse** [comment]
I can reproduce this locally:

```
Running locally via bundle ...
[metanorma] Error: flavor gem metanorma-iso not present
[metanorma] Error: flavor gem metanorma-iec not present
[metanorma] Error: flavor gem metanorma-ietf not present
[metanorma] Error: flavor gem metanorma-gb not present
[metanorma] Error: flavor gem metanorma-cc not present
[metanorma] Error: flavor gem metanorma-csa not present
[metanorma] Error: flavor gem metanorma-iho not present
[metanorma] Error: flavor gem metanorma-m3aawg not present
[metanorma] Error: flavor gem metanorma-generic not present
[metanorma] Error: flavor gem metanorma-standoc not present
[metanorma] Error: flavor gem metanorma-un not present
[metanorma] Error: flavor gem metanorma-nist not present
[metanorma] Error: flavor gem metanorma-ogc not present
[metanorma] Error: flavor gem metanorma-itu not present
[metanorma] Error: loading gem `metanorma-itu` failed. Exiting.
```

**Comment by ronaldtse** [comment]
Here's the real error:

```
require 'metanorma-iso.rb'irb(main):001:0> require 'metanorma-iso'
Traceback (most recent call last):
       16: from /Users/me/.rbenv/versions/2.6.5/bin/irb:23:in `load'
       15: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
       14: from (irb):1
       13: from (irb):1:in `require'
       12: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.5.8/lib/metanorma-iso.rb:2:in `<top (required)>'
       11: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.5.8/lib/metanorma-iso.rb:2:in `require_relative'
       10: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.5.8/lib/asciidoctor/iso/converter.rb:2:in `<top (required)>'
        9: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-iso-1.5.8/lib/asciidoctor/iso/converter.rb:2:in `require'
        8: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/metanorma-standoc.rb:3:in `<top (required)>'
        7: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/metanorma-standoc.rb:3:in `require_relative'
        6: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/converter.rb:7:in `<top (required)>'
        5: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/converter.rb:7:in `require'
        4: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/inline.rb:7:in `<top (required)>'
        3: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/metanorma-standoc-1.5.3/lib/asciidoctor/standoc/inline.rb:7:in `require'
        2: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/latexmath-0.1.3/lib/latexmath.rb:1:in `<top (required)>'
        1: from /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/latexmath-0.1.3/lib/latexmath.rb:1:in `require'
LoadError (cannot load such file -- byebug)
```

**Comment by ronaldtse** [comment]
Issue fixed in https://github.com/plurimath/latexmath/commit/1357c73035b37db02dfa164c287fa105518ea0fa

**Comment by ronaldtse** [comment]
Closing this, tests are passing.
