### ISSUE TITLE
Fontist error

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#217]
From @gbuehler:

> I was getting an error on my Mac running the Metanorma scripts.
> 
> ```
> /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/index.rb:7:in `from_yaml': Please fetch index with `fontist update`.
> (Fontist::Errors::FormulaIndexNotFoundError)
> ```
> 
> I found where it seems you were having the same type of issue:
> 
> https://github.com/fontist/fontist/issues/177
> 
> I have installed and updated the fontist gem, but it is missing Arial.
> 
> Did you get it solved?

**Comment by ronaldtse** [comment]
Follow-up from @gbuehler:

Output:
```sh
Greg: greg$ fontist install 'arial'
Fonts found at:
- /Library/Fonts/Arial Bold.ttf
- /Library/Fonts/Arial.ttf
- /Library/Fonts/Arial Bold Italic.ttf
- /Library/Fonts/Arial Italic.ttf
- /Applications/Microsoft Word.app/Contents/Resources/DFonts/arialbd.ttf
- /Applications/Microsoft Word.app/Contents/Resources/DFonts/arial.ttf
- /Applications/Microsoft Word.app/Contents/Resources/DFonts/ariblk.ttf
- /Applications/Microsoft Word.app/Contents/Resources/DFonts/ariali.ttf
- /Applications/Microsoft Word.app/Contents/Resources/DFonts/arialbi.ttf
- /Applications/Microsoft Excel.app/Contents/Resources/DFonts/arialbd.ttf
- /Applications/Microsoft Excel.app/Contents/Resources/DFonts/arial.ttf
- /Applications/Microsoft Excel.app/Contents/Resources/DFonts/ariblk.ttf
- /Applications/Microsoft Excel.app/Contents/Resources/DFonts/ariali.ttf
- /Applications/Microsoft Excel.app/Contents/Resources/DFonts/arialbi.ttf
- /Applications/Microsoft Outlook.app/Contents/Resources/DFonts/arialbd.ttf
- /Applications/Microsoft Outlook.app/Contents/Resources/DFonts/arial.ttf
- /Applications/Microsoft Outlook.app/Contents/Resources/DFonts/ariblk.ttf
- /Applications/Microsoft Outlook.app/Contents/Resources/DFonts/ariali.ttf
- /Applications/Microsoft Outlook.app/Contents/Resources/DFonts/arialbi.ttf
- /Applications/Microsoft OneNote.app/Contents/Resources/DFonts/arialbd.ttf
- /Applications/Microsoft OneNote.app/Contents/Resources/DFonts/arial.ttf
- /Applications/Microsoft OneNote.app/Contents/Resources/DFonts/ariblk.ttf
- /Applications/Microsoft OneNote.app/Contents/Resources/DFonts/ariali.ttf
- /Applications/Microsoft OneNote.app/Contents/Resources/DFonts/arialbi.ttf
- /Applications/Microsoft PowerPoint.app/Contents/Resources/DFonts/arialbd.ttf
- /Applications/Microsoft PowerPoint.app/Contents/Resources/DFonts/arial.ttf
- /Applications/Microsoft PowerPoint.app/Contents/Resources/DFonts/ariblk.ttf
- /Applications/Microsoft PowerPoint.app/Contents/Resources/DFonts/ariali.ttf
- /Applications/Microsoft PowerPoint.app/Contents/Resources/DFonts/arialbi.ttf
Greg: greg$ fontist status arial
'arial' font is missing, please run `fontist install 'arial'` to download the font.
```

Obviously, that did not work.

```
================
FONT LICENSE ACCEPTANCE REQUIRED FOR "Arial":

Fontist can install this font if you accept its licensing conditions.

FONT LICENSE BEGIN ("Arial")
-----------------------------------------------------------------------
(from http://web.archive.org/web/20011222020409/http://www.microsoft.com/typography/fontpack/eula.htm)
TrueType core fonts for the Web EULA...
```

Here is the output from running command:
```
docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma compile -t ogc -x xml,html,doc,pdf document.adoc
-----------------------------------------------------------------------

FONT LICENSE END ("Arial")
/usr/local/bundle/gems/fontist-1.8.4/lib/fontist/font.rb:120:in `check_and_confirm_required_license': Fontist will not download these fonts unless you accept the terms. (Fontist::Errors::LicensingError)
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/font.rb:105:in `download_font'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/font.rb:42:in `install'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/font.rb:22:in `install'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/install.rb:23:in `install_font'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/install.rb:17:in `file_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:50:in `map'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:50:in `style_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:38:in `each'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:38:in `map'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:38:in `font_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:26:in `call'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:21:in `from_hash'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:312:in `fontist_install'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:308:in `rescue in install_fonts_safe'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:292:in `install_fonts_safe'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:287:in `install_fonts'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:27:in `compile'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/compiler.rb:45:in `compile_file'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/compiler.rb:30:in `compile'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/compiler.rb:35:in `compile'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/command.rb:42:in `compile'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli.rb:62:in `start'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/exe/metanorma:20:in `<top (required)>'
from /usr/local/bundle/bin/metanorma:23:in `load'
from /usr/local/bundle/bin/metanorma:23:in `<main>'
/usr/local/bundle/gems/fontist-1.8.4/lib/fontist/index.rb:7:in `from_yaml': Please fetch index with `fontist update`. (Fontist::Errors::FormulaIndexNotFoundError)
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/formula.rb:28:in `find_fonts'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/formula_paths.rb:30:in `find_styles_by_formulas'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/formula_paths.rb:10:in `find'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/system_font.rb:75:in `find_by_formulas'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/system_font.rb:67:in `find_styles'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/system_font.rb:55:in `find_with_name'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/system_font.rb:44:in `find_with_name'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:64:in `find_font_with_name'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/install.rb:14:in `file_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:50:in `map'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:50:in `style_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:38:in `each'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:38:in `map'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:38:in `font_paths'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:26:in `call'
from /usr/local/bundle/gems/fontist-1.8.4/lib/fontist/manifest/locations.rb:21:in `from_hash'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:312:in `fontist_install'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:293:in `install_fonts_safe'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:287:in `install_fonts'
from /usr/local/bundle/gems/metanorma-1.2.4/lib/metanorma/compile.rb:27:in `compile'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/compiler.rb:45:in `compile_file'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/compiler.rb:30:in `compile'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/compiler.rb:35:in `compile'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli/command.rb:42:in `compile'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/lib/metanorma/cli.rb:62:in `start'
from /usr/local/bundle/bundler/gems/metanorma-cli-eb2534021b79/exe/metanorma:20:in `<top (required)>'
from /usr/local/bundle/bin/metanorma:23:in `load'
from /usr/local/bundle/bin/metanorma:23:in `<main>'

<wnload these fonts for you? => TYPE 'Yes' or 'No': 
================
```

**Comment by CAMOBAP** [comment]
As workaround:

Because we have defined `ENV DEBIAN_FRONTEND=noninteractive` https://github.com/metanorma/metanorma-docker/blob/master/Dockerfile.ubuntu.in#L8

It makes sense to try with `--agree-to-terms` i.e. 

`docker run -v "$(pwd)":/metanorma metanorma/mn  metanorma compile -t ogc -x xml,html,doc,pdf --agree-to-terms document.adoc`

cc @ronaldtse @gbuehler

**Comment by ronaldtse** [comment]
Maybe there are two problems here:

1. `fontist status arial` can't find the font on @gbuhler's Mac, causing Metanorma to re-download the font. However, the `fontist install arial` command says that the font is already installed, hence Metanorma is unable to use Arial.

2. Docker runs fail because of the missing `--agree-to-terms`. This should be solved via metanorma/metanorma-cli#216.

**Comment by CAMOBAP** [comment]
> Docker runs fail because of the missing --agree-to-terms. This should be solved via #216.

@ronaldtse `--agree-to-terms` already available for `compile` command. #216 PR about the possibility to declare arguments in the config file, so #216 doesn't block this issue

**Comment by ronaldtse** [comment]
@gbuhler : @CAMOBAP confirms that the above command (https://github.com/metanorma/metanorma-cli/issues/217#issuecomment-763566201) works, can you have a try? Thanks!

**Comment by CAMOBAP** [comment]
@gbuhler in case of any issues please try a fresh version of `metanorma/mn` image first

**Comment by gbuehler** [comment]
@ronaldtse @CAMOBAP  That works fine with my setup.

**Comment by ronaldtse** [comment]
Thanks @gbuehler!

**Comment by ronaldtse** [comment]
In any case fontist/fontist#209 still persists.

We also need to update documentation to reflect the latest command update. @CAMOBAP can you make the update for metanorma.com? Thanks.

**Comment by CAMOBAP** [comment]
I have looked at https://github.com/metanorma/metanorma-cli/issues/217#issuecomment-763555922 again and the behavior of metanorma-cli side looks correct.

> We also need to update documentation to reflect the latest command update. @CAMOBAP can you make the update for metanorma.com? Thanks.

On it

**Comment by CAMOBAP** [comment]
documentation is ready for review https://github.com/metanorma/metanorma.com/pull/394

**Comment by CAMOBAP** [comment]
Because documentation is updated and the separate issue is reported to https://github.com/fontist/fontist/issues/209, this one can be closed
