### ISSUE TITLE
metanorma new incorrect handling path on winows

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#263]
https://github.com/actions-mn/cli/runs/4593740924?check_suite_focus=true

```
C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir': Invalid argument @ dir_s_mkdir - D:/a/cli/cli/test/C: (Errno::EINVAL)
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:211:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/generator.rb:111:in `create_file'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/generator.rb:58:in `block in create_metanorma_document'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/generator.rb:58:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/generator.rb:58:in `create_metanorma_document'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/generator.rb:24:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/generator.rb:42:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/command.rb:205:in `create_new_document'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli/command.rb:23:in `new'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.5.4/lib/metanorma/cli.rb:34:in `start'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1EAF.tmp/src/metanorma:212:in `<main>'
```

**Comment by CAMOBAP** [comment]
This particular issue is already fixed but still not released in packed-mn (1.5.5 is broken). Proof: https://github.com/actions-mn/cli/runs/4853268919?check_suite_focus=true

**Comment by ronaldtse** [comment]
@CAMOBAP but packed-mn is fully passing now: https://github.com/metanorma/packed-mn/actions

How can we trigger a new release?

**Comment by CAMOBAP** [comment]
Yep I will trigger the release, BTW I just found that metanorma-cli trigger was broken so I will fix it first

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP !
