### ISSUE TITLE
--no-install-fonts looks broken

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#266]
### Intro

During GitHub Actions configuration update for `mn-templates-nist`, I have found that we call mn2pdf when `--no-install-fonts` passed.

### Problem

Because `mn2pdf` heavily depends on fonts it fails with 

<details>
  <summary>java.io.FileNotFoundException</summary>

```

[INFO] XSL-FO file preparation...
Transforming to PDF...
WARNING: Font file '/root/.metanorma/fonts/arial.ttf' (font name 'Arial', font style 'normal', font weight 'normal') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/root/.metanorma/fonts/arialbd.ttf' (font name 'Arial', font style 'normal', font weight 'bold') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/root/.metanorma/fonts/arialbi.ttf' (font name 'Arial', font style 'italic', font weight 'bold') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/root/.metanorma/fonts/ariali.ttf' (font name 'Arial', font style 'italic', font weight 'normal') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-It.ttf'.
WARNING: Font file '/root/.metanorma/fonts/times.ttf' (font name 'Times New Roman', font style 'normal', font weight 'normal') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-Regular.ttf'.
WARNING: Font file '/root/.metanorma/fonts/timesbd.ttf' (font name 'Times New Roman', font style 'normal', font weight 'bold') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-Bold.ttf'.
WARNING: Font file '/root/.metanorma/fonts/timesbi.ttf' (font name 'Times New Roman', font style 'italic', font weight 'bold') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-BoldIt.ttf'.
WARNING: Font file '/root/.metanorma/fonts/timesi.ttf' (font name 'Times New Roman', font style 'italic', font weight 'normal') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-It.ttf'.

Default page-height set to: 11.00in
Default page-width set to: 8.50in
Content overflows the viewport of an fo:block-container in block-progression direction by 444 millipoints. (See position 1:5599)
Failed to read font file file:/root/.metanorma/fonts/calibri.ttf
java.io.FileNotFoundException: /root/.metanorma/fonts/calibri.ttf (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at java.base/java.net.URL.openStream(URL.java:1165)
	at org.apache.fop.apps.io.ResourceResolverFactory$NormalResourceResolver.getResource(ResourceResolverFactory.java:224)
	at org.apache.fop.apps.io.ResourceResolverFactory$TempAwareResourceResolver.getResource(ResourceResolverFactory.java:152)
	at org.apache.fop.apps.io.ResourceResolverFactory$DefaultResourceResolver.getResource(ResourceResolverFactory.java:121)
	at org.apache.fop.apps.io.InternalResourceResolver.getResource(InternalResourceResolver.java:92)
	at org.apache.fop.fonts.truetype.OFFontLoader.read(OFFontLoader.java:111)
	at org.apache.fop.fonts.truetype.OFFontLoader.read(OFFontLoader.java:101)
	at org.apache.fop.fonts.FontLoader.getFont(FontLoader.java:126)
	at org.apache.fop.fonts.FontLoader.loadFont(FontLoader.java:110)
	at org.apache.fop.fonts.LazyFont.load(LazyFont.java:119)
	at org.apache.fop.fonts.LazyFont.hasChar(LazyFont.java:179)
	at org.apache.fop.fonts.Font.hasChar(Font.java:278)
	at org.apache.fop.svg.font.FOPGVTFont.canDisplay(FOPGVTFont.java:54)
	at org.apache.fop.svg.font.FOPGVTFont.canDisplayUpTo(FOPGVTFont.java:69)
	at org.apache.batik.bridge.StrokingTextPainter.createModifiedACIForFontMatching(StrokingTextPainter.java:476)
	at org.apache.batik.bridge.StrokingTextPainter.computeTextRuns(StrokingTextPainter.java:225)
	at org.apache.fop.svg.NativeTextPainter.computeTextRuns(NativeTextPainter.java:224)
	at org.apache.batik.bridge.StrokingTextPainter.getTextRuns(StrokingTextPainter.java:192)
	at org.apache.batik.bridge.StrokingTextPainter.getBounds2D(StrokingTextPainter.java:1083)
	at org.apache.batik.bridge.TextNode.getPrimitiveBounds(TextNode.java:243)
	at org.apache.batik.gvt.AbstractGraphicsNode.getTransformedPrimitiveBounds(AbstractGraphicsNode.java:854)
	at org.apache.batik.gvt.AbstractGraphicsNode.getTransformedBounds(AbstractGraphicsNode.java:820)
	at org.apache.batik.gvt.CompositeGraphicsNode.getTransformedPrimitiveBounds(CompositeGraphicsNode.java:301)
	at org.apache.batik.gvt.AbstractGraphicsNode.getTransformedBounds(AbstractGraphicsNode.java:820)
	at org.apache.batik.gvt.CompositeGraphicsNode.getPrimitiveBounds(CompositeGraphicsNode.java:207)
	at org.apache.batik.gvt.CompositeGraphicsNode.getTransformedPrimitiveBounds(CompositeGraphicsNode.java:295)
	at org.apache.batik.gvt.AbstractGraphicsNode.getTransformedBounds(AbstractGraphicsNode.java:820)
	at org.apache.batik.gvt.CompositeGraphicsNode.getPrimitiveBounds(CompositeGraphicsNode.java:207)
	at org.apache.batik.gvt.AbstractGraphicsNode.getBounds(AbstractGraphicsNode.java:768)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:443)
	at org.apache.fop.render.pdf.PDFImageHandlerSVG.handleImage(PDFImageHandlerSVG.java:208)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:249)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImage(AbstractIFPainter.java:205)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingImageHandler(AbstractIFPainter.java:170)
	at org.apache.fop.render.intermediate.AbstractIFPainter.drawImageUsingDocument(AbstractIFPainter.java:319)
	at org.apache.fop.render.pdf.PDFPainter.drawImage(PDFPainter.java:289)
	at org.apache.fop.render.intermediate.IFRenderer.renderForeignObject(IFRenderer.java:1319)
	at org.apache.fop.render.AbstractRenderer.renderInlineViewport(AbstractRenderer.java:1034)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderInlineViewport(AbstractPathOrientedRenderer.java:836)
	at org.apache.fop.render.intermediate.IFRenderer.renderInlineViewport(IFRenderer.java:863)
	at org.apache.fop.render.AbstractRenderer.renderInlineArea(AbstractRenderer.java:877)
	at org.apache.fop.render.intermediate.IFRenderer.renderInlineArea(IFRenderer.java:927)
	at org.apache.fop.render.AbstractRenderer.renderLineArea(AbstractRenderer.java:845)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:704)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:758)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderReferenceArea(AbstractPathOrientedRenderer.java:759)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:744)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlockViewport(IFRenderer.java:812)
	at org.apache.fop.render.AbstractRenderer.renderBlock(AbstractRenderer.java:737)
	at org.apache.fop.render.intermediate.IFRenderer.renderBlock(IFRenderer.java:999)
	at org.apache.fop.render.AbstractRenderer.renderBlocks(AbstractRenderer.java:689)
	at org.apache.fop.render.AbstractRenderer.renderFlow(AbstractRenderer.java:591)
	at org.apache.fop.render.AbstractPathOrientedRenderer.renderFlow(AbstractPathOrientedRenderer.java:789)
	at org.apache.fop.render.AbstractRenderer.renderMainReference(AbstractRenderer.java:568)
	at org.apache.fop.render.AbstractRenderer.renderBodyRegion(AbstractRenderer.java:433)
	at org.apache.fop.render.AbstractRenderer.renderRegionViewport(AbstractRenderer.java:380)
	at org.apache.fop.render.intermediate.IFRenderer.renderRegionViewport(IFRenderer.java:738)
	at org.apache.fop.render.AbstractRenderer.renderPageAreas(AbstractRenderer.java:345)
	at org.apache.fop.render.AbstractRenderer.renderPage(AbstractRenderer.java:318)
	at org.apache.fop.render.intermediate.IFRenderer.renderPage(IFRenderer.java:587)
	at org.apache.fop.area.RenderPagesModel.renderPage(RenderPagesModel.java:193)
	at org.apache.fop.area.RenderPagesModel.checkPreparedPages(RenderPagesModel.java:174)
	at org.apache.fop.area.RenderPagesModel.addPage(RenderPagesModel.java:146)
	at org.apache.fop.layoutmgr.AbstractPageSequenceLayoutManager.finishPage(AbstractPageSequenceLayoutManager.java:316)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.finishPage(PageSequenceLayoutManager.java:243)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:147)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.DelegatingFOEventHandler.endPageSequence(DelegatingFOEventHandler.java:114)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endPageSequence(FO2StructureTreeConverter.java:184)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:428)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:314)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:192)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:174)


```

</details>

[More logs](https://github.com/metanorma/mn-templates-nist/runs/4747717604?check_suite_focus=true#step:7:120)

### Proposed solution

1. Don't call for `mn2pdf` if `--no-install-fonts` passed
2. remove `--no-install-fonts` option at all
3. @Intelligent2013 maybe there is some other graceful way to handle it on `mn2pdf`

@ronaldtse @Intelligent2013 feel free to share your vision

**Comment by Intelligent2013** [comment]
Usually mn2pdf substitutes SourceSans/Serif fonts for non found fonts, for instance:
```
WARNING: Font file '/root/.metanorma/fonts/arialbi.ttf' (font name 'Arial', font style 'italic', font weight 'bold') doesn't exist. Replaced by '/root/.metanorma/fonts/SourceSansPro-BoldIt.ttf'
```

but something wrong for Calibri font... I have to investigate it.

**Comment by Intelligent2013** [comment]
@CAMOBAP issue fixed. Updated xslt: https://github.com/metanorma/metanorma-nist/blob/main/lib/isodoc/nist/nist.cswp.xsl
