### ISSUE TITLE
Crash in PDF generation does not show any error message, but PDF file has size 0

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#274]
Failure in processing within Mnconvert does not produce any error in the command output, and hides all error messages.

What is the correct behavior here? I believe we want to:
1. Keep processing files that have not failed.
2. For the files that failed, we need to show which file has failed and the error messages for it, collected during process and displaying at the end (like RSpec output).
3. The command should return an error (separate error codes for, e.g: no failure 0, crash 1, some documents failed to process 2).

```sh
$ bundle exec metanorma site generate
[info]: Compiling /Users/me/src/iso-15926-6/iso15926-6ed2n-en.adoc ...
...
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.41.1/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/iso-15926-6/site/documents/iso15926-6ed2n-en.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.0.8/lib/isodoc/iso/iso.international-standard.xsl" --pdf-file "/Users/me/src/iso-15926-6/site/documents/iso15926-6ed2n-en.pdf" --param baseassetpath="/Users/me/Downloads/WIP_15APR2022(苑田)" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20220420-32299-drauld.yml"
[info]: Building collection file: /Users/me/src/iso-15926-6/site/documents.xml ...
[info]: Generating html site in /Users/me/src/iso-15926-6/site ...
Site has been generated at /Users/me/src/iso-15926-6/site
$
```

```sh
$ bundle exec metanorma iso15926-6ed2n-en.adoc 
...
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/mn2pdf-1.41.1/lib/../bin/mn2pdf.jar --xml-file "/Users/me/src/iso-15926-6/iso15926-6ed2n-en.presentation.xml" --xsl-file "/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.0.8/lib/isodoc/iso/iso.international-standard.xsl" --pdf-file "/Users/me/src/iso-15926-6/iso15926-6ed2n-en.pdf" --syntax-highlight  --font-manifest "/var/folders/2t/xmdrn2sd2lv2w49dv0zw9_q00000gp/T/fontist_locations20220420-31231-15cawl.yml"
[mn2pdf] Fatal: mn2pdf Preparing...
Input: XML (/Users/me/src/iso-15926-6/iso15926-6ed2n-en.presentation.xml)
Input: XSL (/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/metanorma-iso-2.0.8/lib/isodoc/iso/iso.international-standard.xsl)
Output: PDF (/Users/me/src/iso-15926-6/iso15926-6ed2n-en.pdf)

[INFO] XSL-FO file preparation...
Transforming to PDF...
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
java.awt.FontFormatException: bad pfa font
	at java.desktop/sun.font.Type1Font.verifyPFA(Type1Font.java:321)
	at java.desktop/sun.font.Type1Font.verify(Type1Font.java:299)
	at java.desktop/sun.font.Type1Font.<init>(Type1Font.java:172)
	at java.desktop/sun.font.SunFontManager.createFont2D(SunFontManager.java:2258)
	at java.desktop/java.awt.Font.<init>(Font.java:615)
	at java.desktop/java.awt.Font.createFont(Font.java:1219)
	at org.metanorma.fop.fontConfig.registerFont(fontConfig.java:785)
	at org.metanorma.fop.fontConfig.lambda$updateFontsForGraphicsEnvironment$28(fontConfig.java:768)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.metanorma.fop.fontConfig.updateFontsForGraphicsEnvironment(fontConfig.java:767)
	at org.metanorma.fop.fontConfig.updateConfig(fontConfig.java:445)
	at org.metanorma.fop.fontConfig.getConfig(fontConfig.java:736)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:447)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:394)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:272)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:334)
Default page-height set to: 11.00in
Default page-width set to: 8.50in
This is a TrueType collection file with 2 fonts
Containing the following fonts: 
Cambria <-- selected
Cambria Math
Rendered page #1.
Rendered page #2.
An fo:block  (See position 40:669) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
An fo:block  (See position 40:1418) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
An fo:block  (See position 40:31546) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
An fo:block  (See position 40:32547) is wider than the available room in inline-progression-dimension. Adjusting end-indent based on overconstrained geometry rules (XSL 1.1, ch. 5.3.4)
org.apache.batik.bridge.BridgeException: Unexpected character (code: 78).
	at org.apache.batik.bridge.UnitProcessor.svgToUserSpace(UnitProcessor.java:313)
	at org.apache.batik.bridge.UnitProcessor.svgLengthToUserSpace(UnitProcessor.java:286)
	at org.apache.batik.bridge.UnitProcessor.svgHorizontalLengthToUserSpace(UnitProcessor.java:203)
	at org.apache.fop.fo.extensions.svg.SVGElement.getSize(SVGElement.java:164)
	at org.apache.fop.fo.extensions.svg.SVGElement.getDimension(SVGElement.java:142)
	at org.apache.fop.fo.flow.InstreamForeignObject.prepareIntrinsicSize(InstreamForeignObject.java:112)
	at org.apache.fop.fo.flow.InstreamForeignObject.getIntrinsicWidth(InstreamForeignObject.java:125)
	at org.apache.fop.layoutmgr.inline.AbstractGraphicsLayoutManager.getInlineArea(AbstractGraphicsLayoutManager.java:61)
	at org.apache.fop.layoutmgr.inline.AbstractGraphicsLayoutManager.getNextKnuthElements(AbstractGraphicsLayoutManager.java:116)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.collectInlineKnuthElements(LineLayoutManager.java:698)
	at org.apache.fop.layoutmgr.inline.LineLayoutManager.getNextKnuthElements(LineLayoutManager.java:627)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:292)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:292)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextChildElements(BlockStackingLayoutManager.java:501)
	at org.apache.fop.layoutmgr.BlockContainerLayoutManager.getNextKnuthElements(BlockContainerLayoutManager.java:256)
	at org.apache.fop.layoutmgr.BlockContainerLayoutManager.getNextKnuthElements(BlockContainerLayoutManager.java:186)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:292)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:292)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:292)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextChildElements(BlockLayoutManager.java:141)
	at org.apache.fop.layoutmgr.BlockStackingLayoutManager.getNextKnuthElements(BlockStackingLayoutManager.java:292)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:113)
	at org.apache.fop.layoutmgr.BlockLayoutManager.getNextKnuthElements(BlockLayoutManager.java:105)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextChildElements(FlowLayoutManager.java:223)
	at org.apache.fop.layoutmgr.FlowLayoutManager.addChildElements(FlowLayoutManager.java:148)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:116)
	at org.apache.fop.layoutmgr.FlowLayoutManager.getNextKnuthElements(FlowLayoutManager.java:69)
	at org.apache.fop.layoutmgr.PageBreaker.getNextKnuthElements(PageBreaker.java:251)
	at org.apache.fop.layoutmgr.AbstractBreaker.getNextBlockList(AbstractBreaker.java:675)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:178)
	at org.apache.fop.layoutmgr.PageBreaker.getNextBlockList(PageBreaker.java:158)
	at org.apache.fop.layoutmgr.AbstractBreaker.doLayout(AbstractBreaker.java:385)
	at org.apache.fop.layoutmgr.PageBreaker.doLayout(PageBreaker.java:112)
	at org.apache.fop.layoutmgr.PageSequenceLayoutManager.activateLayout(PageSequenceLayoutManager.java:143)
	at org.apache.fop.area.AreaTreeHandler.endPageSequence(AreaTreeHandler.java:267)
	at org.apache.fop.fo.DelegatingFOEventHandler.endPageSequence(DelegatingFOEventHandler.java:114)
	at org.apache.fop.accessibility.fo.FO2StructureTreeConverter.endPageSequence(FO2StructureTreeConverter.java:184)
	at org.apache.fop.fo.pagination.PageSequence.endOfNode(PageSequence.java:139)
	at org.apache.fop.fo.FOTreeBuilder$MainFOHandler.endElement(FOTreeBuilder.java:362)
	at org.apache.fop.fo.FOTreeBuilder.endElement(FOTreeBuilder.java:190)
	at org.apache.xalan.transformer.TransformerIdentityImpl.endElement(TransformerIdentityImpl.java:1102)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1727)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2898)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at org.apache.xalan.transformer.TransformerIdentityImpl.transform(TransformerIdentityImpl.java:485)
	at org.metanorma.fop.PDFGenerator.runFOP(PDFGenerator.java:509)
	at org.metanorma.fop.PDFGenerator.convertmn2pdf(PDFGenerator.java:394)
	at org.metanorma.fop.PDFGenerator.process(PDFGenerator.java:272)
	at org.metanorma.fop.mn2pdf.main(mn2pdf.java:334)
XSL-FO file for debugging saved into: /Users/me/src/iso-15926-6/iso15926-6ed2n-en.pdf.fo.debug.xml
```

**Comment by CAMOBAP** [comment]
The issue doesn't reproduced on the last CI runs for iso-15926-6 https://github.com/metanorma/iso-15926-6/runs/6683304131?check_suite_focus=true

I will double-check and rerun once 1.5.16 metanorma-snap is released

**Comment by ronaldtse** [comment]
This problem still occurs. When PDF generation breaks, there is no error message.
See https://github.com/metanorma/iso-34000/pull/1 .

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/metanorma-standoc/issues/648 fixed
