### ISSUE TITLE
There is a crossreference to an instance of formula nested within formula:  target="eq9"

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#300]
Error was found during the release of `1.6.14.pre`

```
Metanorma XML Style Warning: (XML Line 001222): Figure should have title
Metanorma XML Style Warning: (XML Line 001229): Figure should have title
Metanorma XML Style Warning: (XML Line 001236): Figure should have title
Metanorma XML Style Warning: (XML Line 001242): Figure should have title
Metanorma XML Style Warning: (XML Line 001254): Figure should have title
Metanorma XML Style Warning: (XML Line 001261): Figure should have title
Metanorma XML Style Warning: (XML Line 001267): Figure should have title
Metanorma XML Style Warning: (XML Line 001273): Figure should have title
There is a crossreference to an instance of formula nested within formula:  target="eq9"
Error: Process completed with exit code 1.
```

Also, it looks like mn2pdf didn't finish successfully

```
java -Xss5m -Xmx2048m -Dapple.awt.UIElement=true -jar /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20230227-2095-gqa8fk/mn2pdf.jar --xml-file "/Users/runner/work/packed-mn/packed-mn/site-jcgm/documents/jcgm/100-2008-en/document.presentation.xml" --xsl-file "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/packed-mn-20230227-2095-gqa8fk/jcgm.standard.xsl" --pdf-file "/Users/runner/work/packed-mn/packed-mn/site-jcgm/documents/jcgm/100-2008-en/document.pdf" --param baseassetpath="/Users/runner/work/packed-mn/packed-mn/samples/sources/jcgm/100-2008-en" --syntax-highlight  --font-manifest "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/fontist_locations20230227-2095-1lzfwz4.yml"
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:79:in `mn2pdf'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:54:in `block in convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:100:in `block in dump_fontist_manifest_locations'
/__tebako_memfs__/lib/ruby/2.7.0/tempfile.rb:332:in `create'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:96:in `dump_fontist_manifest_locations'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/mn2pdf-1.62/lib/mn2pdf.rb:52:in `convert'
/__tebako_memfs__/local/metanorma:119:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.4.5/lib/metanorma/output/xslfo.rb:10:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/isodoc-2.4.5/lib/isodoc/xslfo_convert.rb:59:in `convert'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-bipm-2.2.5/lib/metanorma/bipm/processor.rb:50:in `output'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/compile.rb:150:in `process_output_threaded'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/compile.rb:142:in `block in process_exts1'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:9:in `loop'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:8:in `catch'
/__tebako_memfs__/lib/ruby/gems/2.7.0/gems/metanorma-1.5.6/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'
```

Full logs: https://github.com/metanorma/packed-mn/actions/runs/4282122540/jobs/7456454542

cc @ronaldtse 

P.S. after merge https://github.com/metanorma/metanorma-cli/pull/295 we will get such errors earlier on metanorma-cli CI

**Comment by Intelligent2013** [comment]
I've repeated the issue:
```
git clone https://github.com/metanorma/mn-samples-jcgm
cd mn-samples-jcgm
bundle update
cd sources/jcgm/100-2008-en
bundle exec metanorma -t bipm -x pdf document.adoc
```

Error in JCGM XSLT:
```
[FATAL] Missing attribute on fo:bookmark: Either external-destination or internal-destination must be specified. (See position 1:50670)
```

Will investigate.

**Comment by Intelligent2013** [comment]
@CAMOBAP `System.stderr`.
mn2pdf generates `...pdf.err` file in case of errors. May be just show the content from it (if exists)?

**Comment by Intelligent2013** [comment]
@CAMOBAP  error in JCGM XSLT fixed in https://github.com/metanorma/metanorma-bipm/blob/main/lib/isodoc/bipm/jcgm.standard.xsl
Now the PDF should be processed successfully.

**Comment by CAMOBAP** [comment]
@opoudjis is that ok to release melanoma-bipm ?

**Comment by opoudjis** [comment]
Is the "eq9" issue related, @Intelligent2013 ? https://github.com/metanorma/mn-samples-jcgm/issues/18

**Comment by Intelligent2013** [comment]
> Is the "eq9" issue related, @Intelligent2013 ? [metanorma/mn-samples-jcgm#18](https://github.com/metanorma/mn-samples-jcgm/issues/18)

@opoudjis no, there was the issue in JCGM XSLT due wrong XPaths. The message `There is a crossreference to an instance of formula nested within formula:  target="eq9"` relates to the metanorma gem step.

**Comment by opoudjis** [comment]
So there are two issues. 

* https://github.com/metanorma/mn-samples-jcgm/issues/19
* https://github.com/metanorma/mn-samples-jcgm/issues/18

This ticket stays on hold as a placeholder

**Comment by opoudjis** [comment]
Document generates now locally.

**Comment by opoudjis** [comment]
No, not released, sorry.

**Comment by ronaldtse** [comment]
@camobap let’s comment out the JCGM documents for now, we should not let those samples affect our release process. Thanks.
