### ISSUE TITLE
Metanotma rake fails for windows on fontist repos

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#303]
### Intro

For somereaso `bundle exec rake` for workflows that runs on `fontist`'s repos are failed on windows:
 - https://github.com/fontist/fontist/actions/runs/4494018964/jobs/7905983841?pr=327
 - https://github.com/fontist/formulas/actions/runs/4469771281/jobs/7852363100

```
  1) Metanorma::Collection render html & build doc, pdf, xml files from YAML collection
     Failure/Error:
       Dir.mktmpdir("rspec-") do |dir|
         ["spec/assets/", "spec/examples/", "spec/fixtures/"].each do |assets|
           tmp_assets = File.join(dir, assets)
           FileUtils.rm_rf tmp_assets
           FileUtils.mkdir_p tmp_assets
           FileUtils.cp_r Dir.glob("#{assets}*"), tmp_assets
         end
         Dir.chdir(dir) { example.run }
       end

     Errno::ENOTEMPTY:
       Directory not empty @ dir_s_rmdir - D:/a/_temp/rspec-20230322-3252-wyd9bp
     # ./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Errno::EACCES:
     #   Permission denied @ apply2files - D:/a/_temp/rspec-20230322-3252-wyd9bp/spec/fixtures/collection/rice-en.final.xml
     #   ./spec/spec_helper.rb:23:in `block (2 levels) in <top (required)>'
```

There is no such issues on `metanorma` repo so this issue need to be investigated

**Comment by ronaldtse** [comment]
@alexeymorozov @CAMOBAP is this issue fixed? If so let's close it. Thanks!
