### ISSUE TITLE
Version command not working

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-cli#98]
The version option doesn't seem working:

```sh
$ bundle exec metanorma -t ogc -v
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bin/metanorma)
NameError: uninitialized constant Metanorma::Ogc::VERSION
Did you mean?  Metanorma::VERSION
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-ogc-0.1.2/lib/metanorma/ogc/processor.rb:22:in `version'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.2.2/lib/metanorma/cli/command.rb:53:in `version'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
  /Users/me/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `di
```

**Comment by ronaldtse** [comment]
Without providing a type, it only shows the version of Metanorma::ISO. It should probably show ALL flavors.

```sh
$ bundle exec metanorma -v
Metanorma::ISO 1.2.2
```

**Comment by ronaldtse** [comment]
The `metanorma -v` and `metanorma version` commands should be identical.

**Comment by abunashir** [comment]
@ronaldtse: Functionality wise this should be good (apart from missing back-end message), once you are happy could you please close this one?

**Comment by ronaldtse** [comment]
Indeed. Thanks!

**Comment by ronaldtse** [comment]
@opoudjis we just need to schedule this for the next release. Thanks.
